import os
from datetime import datetime


base_dir = '/home/harris.se/co2_interaction_converge/'
base_py = '/home/harris.se/dft_adsorption/base_pys/co2_cell.py'
job_file = os.path.join(base_dir, 'run_qe_jobs.sh')
os.makedirs(base_dir, exist_ok=True)

# make files to run CO2 relaxation
vmin = 1
vmax = 15
vacuums = [v for v in range(vmin, vmax + 1)]


lines = [f'# Autogenerated {datetime.now()} from {base_py}\n\n']
with open(base_py, 'r') as f:
    for line in f:
        lines.append(line)

# create copies of the python file
for vac in vacuums:
    run_dir = os.path.join(base_dir, f'run{vac}')
    os.makedirs(run_dir, exist_ok=True)
    fname = os.path.join(run_dir, 'relax.py')
    pattern = 'vacuum=12'
    with open(fname, 'w') as f:
        for line in lines:
            if pattern in line:
                f.write(line.replace(pattern, f'vacuum={vac}'))
            else:
                f.write(line)

run_i_dir = os.path.join(base_dir, 'run$SLURM_ARRAY_TASK_ID')
# write the array job file
with open(job_file, 'w') as f:
    f.write('#!/bin/bash\n\n')
    f.write('#SBATCH --time=24:00:00\n')
    f.write('#SBATCH --job-name=QE_converge\n')
    f.write('#SBATCH --mem=20Gb\n')
    f.write('#SBATCH --partition=short,west\n')
    f.write(f'#SBATCH --array={vmin}-{vmax}\n\n')
    f.write(f'cd {run_i_dir}\n')
    f.write(f'python relax.py\n')

