import os
import re
from datetime import datetime


base_dir = '/home/harris.se/ecut_converge_test/'
base_py = '/home/harris.se/dft_adsorption/s3_co2/co2_ecut.py'
job_file = os.path.join(base_dir, 'run_qe_jobs.sh')
os.makedirs(base_dir, exist_ok=True)

# make files to run CO2 relaxation
ecuts = [25, 36, 47, 58]
ecutrhos = []
for e in ecuts:
    ecutrhos.append(e * 10)

lines = [f'# Autogenerated {datetime.now()} from {base_py}\n\n']
with open(base_py, 'r') as f:
    for line in f:
        lines.append(line)

# create copies of the python file
pattern_ecutwfc = r'ecutwfc\s*:\s*(\d)*'
pattern_ecutrho = r'ecutrho\s*:\s*(\d)*'
for i, ecut in enumerate(ecuts):
    run_dir = os.path.join(base_dir, f'run{ecut}')
    os.makedirs(run_dir, exist_ok=True)
    fname = os.path.join(run_dir, 'relax.py')
    with open(fname, 'w') as f:
        for line in lines:
            match1 = re.search(pattern_ecutwfc, line)
            if match1 is None:
                f.write(line)
            else:
                f.write(line.replace(match1[0], f'ecutwfc: {ecuts[i]}'))
            
            match2 = re.search(pattern_ecutrho, line)
            if match2 is None:
                f.write(line)
            else:
                f.write(line.replace(match2[0], f'ecutrho: {ecutrhos[i]}'))


run_i_dir = os.path.join(base_dir, 'run$SLURM_ARRAY_TASK_ID')
# write the array job file
with open(job_file, 'w') as f:
    f.write('#!/bin/bash\n\n')
    f.write('#SBATCH --time=24:00:00\n')
    f.write('#SBATCH --job-name=QE_converge_ecut\n')
    f.write('#SBATCH --mem=20Gb\n')
    f.write('#SBATCH --partition=short,west\n')
    f.write(f'#SBATCH --array={0}-{len(ecuts) - 1}\n\n')
    f.write(f'cd {run_i_dir}\n')
    f.write(f'python relax.py\n')

